# Generated by Django 5.1.5 on 2025-01-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='year',
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
