# Generated by Django 5.1.5 on 2025-01-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userextra_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
    ]
