# Generated by Django 5.1.5 on 2025-01-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userextra_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
