# Generated by Django 5.1.5 on 2025-01-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userextra_roll_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userextra',
            old_name='is_verify',
            new_name='is_verified',
        ),
    ]
