# Generated by Django 5.1.5 on 2025-01-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_is_verify_userextra_is_verified'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userextra',
            options={'verbose_name_plural': 'User Informations'},
        ),
    ]
