# Generated by Django 5.1.5 on 2025-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userextra_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userextra',
            name='forget_password_token_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
