# Generated by Django 5.1.5 on 2025-02-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userextra_forget_password_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
