# Generated by Django 5.1.5 on 2025-04-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userextra_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='course',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='uu_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userextra',
            name='year',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
