# Generated by Django 5.1.5 on 2025-09-07 16:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userextra_course_alter_userextra_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextra',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
