# Generated by Django 5.1.5 on 2025-01-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
