# Generated by Django 5.1.5 on 2025-01-23 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_eventsubmission_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventticket',
            name='event_submission',
        ),
    ]
