# Generated by Django 5.1.5 on 2025-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_eventticket_event_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='submission_uid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
