# Generated by Django 5.1.5 on 2025-01-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_eventticket_submission_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
            preserve_default=False,
        ),
    ]
