# Generated by Django 5.1.5 on 2025-01-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_eventticket_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='year',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
