# Generated by Django 5.1.5 on 2025-01-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventsubmission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='attendence_taken_by',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
