# Generated by Django 5.1.5 on 2025-01-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventsubmission_attendence_taken_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=True),
        ),
    ]
