# Generated by Django 5.1.5 on 2025-01-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_notify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='year',
            field=models.CharField(max_length=5),
        ),
    ]
