# Generated by Django 5.1.5 on 2025-01-25 10:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_eventsubmission_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='creadet_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
