# Generated by Django 5.1.5 on 2025-01-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_eventticket_creadet_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-upload_time']},
        ),
        migrations.RenameField(
            model_name='eventticket',
            old_name='creadet_at',
            new_name='created_at',
        ),
    ]
