# Generated by Django 5.1.5 on 2025-01-25 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_event_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventticket',
            name='uid',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ticket UID'),
        ),
    ]
