# Generated by Django 5.1.5 on 2025-01-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventticket_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventticket',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
