# Generated by Django 5.1.5 on 2025-01-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_eventticket_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='allowed',
            field=models.BooleanField(default=True),
        ),
    ]
