# Generated by Django 5.1.5 on 2025-01-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_eventsubmission_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='attendence_taken_by',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Attendence Taken By/At '),
        ),
    ]
