# Generated by Django 5.1.5 on 2025-01-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_eventsubmission_attendence_taken_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=True, verbose_name='Notify all users through email'),
        ),
    ]
