# Generated by Django 5.1.5 on 2025-01-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_alter_event_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
