# Generated by Django 5.1.5 on 2025-01-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_event_count_event_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
