# Generated by Django 5.1.5 on 2025-01-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_alter_event_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='leave it blank for auto slug generation'),
        ),
    ]
