# Generated by Django 5.1.5 on 2025-01-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_alter_event_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=True, verbose_name='Notify all users through email (at time of creation)'),
        ),
    ]
