# Generated by Django 5.1.5 on 2025-01-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_alter_event_notify'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_over',
            field=models.BooleanField(default=False),
        ),
    ]
