# Generated by Django 5.1.5 on 2025-01-29 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_event_event_over'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='text_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_over',
            field=models.BooleanField(default=False, verbose_name='Event Over?'),
        ),
    ]
