# Generated by Django 5.1.5 on 2025-01-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_event_text_status_alter_event_event_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status (let he backednend handle it)'),
        ),
    ]
