# Generated by Django 5.1.5 on 2025-01-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0026_alter_event_text_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, null=True, verbose_name='Limit (leave it blank if no limit)'),
        ),
    ]
