# Generated by Django 5.1.5 on 2025-01-29 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_alter_event_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='text_status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Status (let he backend handle it)'),
        ),
    ]
