# Generated by Django 5.1.5 on 2025-01-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_event_text_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, help_text='Limit (leave it blank if no limit)', null=True),
        ),
    ]
