# Generated by Django 5.1.5 on 2025-01-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_alter_event_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_over',
            field=models.BooleanField(default=False, help_text='Mark it True if Event is Over'),
        ),
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, help_text='Limit (leave it blank if no registration limit)', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=True, help_text='Notify all users through email (at time of creation)'),
        ),
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(blank=True, help_text='Slug(leave it blank)', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='text_status',
            field=models.CharField(blank=True, help_text='let he backend handle it', max_length=100, null=True),
        ),
    ]
