# Generated by Django 5.1.5 on 2025-01-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_alter_event_event_over_alter_event_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_over',
            field=models.BooleanField(default=False, help_text='Mark it True if the Event is Over'),
        ),
    ]
