# Generated by Django 5.1.5 on 2025-01-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_event_event_over'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='notify',
            field=models.BooleanField(default=True, help_text='Notify all users through email (at the time of creation)'),
        ),
    ]
