# Generated by Django 5.1.5 on 2025-02-04 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_alter_event_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_img', models.ImageField(blank=True, null=True, upload_to='event_result_photo/')),
                ('second_img', models.ImageField(blank=True, null=True, upload_to='event_result_photo/')),
                ('third_img', models.ImageField(blank=True, null=True, upload_to='event_result_photo/')),
                ('result_announced', models.BooleanField(default=False)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first', to=settings.AUTH_USER_MODEL)),
                ('second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second', to=settings.AUTH_USER_MODEL)),
                ('third', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
