# Generated by Django 5.1.5 on 2025-02-04 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_eventresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-upload_time'], 'verbose_name': '1. Event'},
        ),
        migrations.AlterModelOptions(
            name='eventresult',
            options={'verbose_name': '4. Event Result'},
        ),
        migrations.AlterModelOptions(
            name='eventsubmission',
            options={'verbose_name': '2. Event Submission'},
        ),
        migrations.AlterModelOptions(
            name='eventticket',
            options={'verbose_name': '3. Event Ticket'},
        ),
        migrations.AlterField(
            model_name='eventresult',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='events.event'),
        ),
    ]
