# Generated by Django 5.1.5 on 2025-02-04 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_alter_event_options_alter_eventresult_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventresult',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='events.event'),
        ),
    ]
