# Generated by Django 5.1.5 on 2025-04-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_eventcordinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='offers_certification',
            field=models.BooleanField(default=False),
        ),
    ]
