# Generated by Django 5.1.5 on 2025-04-13 11:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_event_offers_certification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
