# Generated by Django 5.1.5 on 2025-04-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_alter_event_organized_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcordinator',
            name='role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
