# Generated by Django 5.1.5 on 2025-04-14 19:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_eventcordinator_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventcordinator',
            unique_together={('user', 'event')},
        ),
    ]
