# Generated by Django 5.1.5 on 2025-04-15 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_eventcordinator_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='events.event'),
        ),
    ]
