# Generated by Django 5.1.5 on 2025-04-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_eventsubmission_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cert_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
