# Generated by Django 5.1.5 on 2025-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0045_event_cert_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='badge_distributed',
            field=models.BooleanField(default=False),
        ),
    ]
