# Generated by Django 5.1.5 on 2025-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_event_badge_distributed'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.PositiveIntegerField(default=0, help_text='Price of the Event (leave it 0 if free)'),
        ),
    ]
