# Generated by Django 5.1.5 on 2025-09-01 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_temporaryeventsubmission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporaryeventsubmission',
            options={'verbose_name': '6. Temporary Event Submission'},
        ),
    ]
