# Generated by Django 5.1.3 on 2025-09-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_temporaryeventsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
