# Generated by Django 5.1.5 on 2025-09-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_event_created_at_event_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
