# Generated by Django 5.1.5 on 2025-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_eventsubmission_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventsubmission',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
