# Generated by Django 5.1.5 on 2025-09-02 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0049_alter_temporaryeventsubmission_options'),
        ('events', '0051_eventsubmission_created_at_and_more'),
    ]

    operations = [
    ]
