# Generated by Django 5.1.5 on 2025-09-02 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_eventsubmission_gateway_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsubmission',
            name='gateway_response',
        ),
        migrations.RemoveField(
            model_name='eventsubmission',
            name='payment_id',
        ),
    ]
