# Generated by Django 5.1.5 on 2025-09-05 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_remove_eventsubmission_gateway_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='last_date_of_registration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
