# Generated by Django 5.1.5 on 2025-09-02 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_merge_20250902_0220'),
        ('events', '0053_remove_eventsubmission_gateway_response_and_more'),
    ]

    operations = [
    ]
