# Generated by Django 5.1.5 on 2025-09-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_event_approved_by_admin_event_end_date_and_more'),
        ('events', '0054_merge_20250902_2023'),
    ]

    operations = [
    ]
