# Generated by Django 5.1.5 on 2025-09-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_event_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='approved_by_admin',
        ),
    ]
