# Generated by Django 5.1.5 on 2025-09-05 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_merge_20250905_1855'),
        ('events', '0056_remove_event_approved_by_admin'),
    ]

    operations = [
    ]
