# Generated by Django 5.1.5 on 2025-09-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0056_remove_event_approved_by_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
