# Generated by Django 5.1.5 on 2025-09-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_event_approved_at_event_rejected_at'),
        ('events', '0057_merge_20250905_2141'),
    ]

    operations = [
    ]
