# Generated by Django 5.1.5 on 2025-09-06 15:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0057_event_approved_at_event_rejected_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='uid',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, null=True),
        ),
    ]
