# Generated by Django 5.1.5 on 2025-09-06 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_event_uid'),
        ('events', '0058_merge_20250906_0232'),
    ]

    operations = [
    ]
