# Generated by Django 5.1.5 on 2025-09-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_event_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='poster_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
