# Generated by Django 5.1.5 on 2025-09-07 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_event_poster_url'),
        ('events', '0059_merge_0058_event_uid_0058_merge_20250906_0232'),
    ]

    operations = [
    ]
