# Generated by Django 5.1.5 on 2025-09-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_event_poster_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='limit',
            field=models.IntegerField(blank=True, default=0, help_text='Limit (leave it blank if no registration limit)', null=True),
        ),
    ]
