# Generated by Django 5.1.5 on 2025-09-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_alter_event_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enrolled_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
