# Generated by Django 5.1.5 on 2025-09-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_merge_20250907_1515'),
        ('events', '0061_event_enrolled_description'),
    ]

    operations = [
    ]
