# Generated by Django 5.1.5 on 2025-03-20 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RemoveField(
            model_name='examname',
            name='Course',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 'department', 'year')},
        ),
    ]
