# Generated by Django 5.1.5 on 2025-03-20 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0002_alter_course_options_remove_examname_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '5. Department'},
        ),
        migrations.AlterModelOptions(
            name='examname',
            options={'verbose_name': '3. Exam Name'},
        ),
        migrations.AlterModelOptions(
            name='previousyearquestionpaper',
            options={'verbose_name': '1. Previous Year Question Paper'},
        ),
        migrations.AlterModelOptions(
            name='year',
            options={'verbose_name': '4. Year'},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_papers.course')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_papers.year')),
            ],
            options={
                'verbose_name': '2. Subject',
            },
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
    ]
