# Generated by Django 5.1.5 on 2025-03-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0003_alter_course_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examname',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
