# Generated by Django 5.1.5 on 2025-03-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0004_examname_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
