# Generated by Django 5.1.5 on 2025-03-20 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0005_subject_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='previousyearquestionpaper',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='question_papers.subject'),
            preserve_default=False,
        ),
    ]
