# Generated by Django 5.1.5 on 2025-04-14 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question_papers', '0006_previousyearquestionpaper_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '6. Course'},
        ),
    ]
