# Generated by Django 5.1.5 on 2025-04-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
