# Generated by Django 5.1.5 on 2025-04-14 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_alter_badge_badge_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='hash',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
