# Generated by Django 5.1.5 on 2025-01-24 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0009_eventsubmission_attendence_taken_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='memories_images/')),
                ('image_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.ImageField(upload_to='memories_videos/')),
                ('video_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Memories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_title', models.CharField(blank=True, max_length=100, null=True)),
                ('memory_date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
            ],
        ),
    ]
