# Generated by Django 5.1.5 on 2025-01-24 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryimages',
            name='memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memories.memories'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='memoryvideo',
            name='memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memories.memories'),
            preserve_default=False,
        ),
    ]
