# Generated by Django 5.1.5 on 2025-01-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_memoryimages_memory_memoryvideo_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryvideo',
            name='video',
            field=models.FileField(upload_to='memories_videos/'),
        ),
    ]
