# Generated by Django 5.1.5 on 2025-01-24 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0003_alter_memoryvideo_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryimages',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_img', to='memories.memories'),
        ),
        migrations.AlterField(
            model_name='memoryvideo',
            name='memory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_vdo', to='memories.memories'),
        ),
    ]
