# Generated by Django 5.1.5 on 2025-01-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0004_alter_memoryimages_memory_alter_memoryvideo_memory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memoryimages',
            options={'get_latest_by': 'image_date'},
        ),
    ]
