# Generated by Django 5.1.5 on 2025-01-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0005_alter_memoryimages_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memories',
            options={'verbose_name_plural': 'Memories'},
        ),
        migrations.AlterModelOptions(
            name='memoryimages',
            options={'get_latest_by': 'image_date', 'verbose_name_plural': 'Memory Images'},
        ),
        migrations.AlterModelOptions(
            name='memoryvideo',
            options={'verbose_name_plural': 'Memory Videos'},
        ),
    ]
