# Generated by Django 5.1.5 on 2025-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0006_alter_memories_options_alter_memoryimages_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memories',
            options={'verbose_name': '1. Memory'},
        ),
        migrations.AlterModelOptions(
            name='memoryimages',
            options={'get_latest_by': 'image_date', 'verbose_name': '2. Memory Image'},
        ),
        migrations.AlterModelOptions(
            name='memoryvideo',
            options={'verbose_name': '3. Memory Video'},
        ),
    ]
