# Generated by Django 5.1.5 on 2025-03-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0007_alter_memories_options_alter_memoryimages_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='memory_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
