# Generated by Django 5.1.5 on 2025-01-25 07:05

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
