# Generated by Django 5.1.5 on 2025-02-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_user'),
        ('events', '0037_alter_eventresult_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name': '1. Blog'},
        ),
        migrations.AddField(
            model_name='blog',
            name='related_event',
            field=models.ForeignKey(blank=True, help_text='Select if the blog is related to the event else leave it', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event'),
        ),
    ]
