# Generated by Django 5.1.5 on 2025-09-15 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_blog_auto_save_data_blog_deleted_at_blog_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={'ordering': ['-created_at'], 'verbose_name': '2. Blog Comment'},
        ),
    ]
