# Generated by Django 5.1.5 on 2025-04-15 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_alter_eventcordinator_unique_together'),
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polloption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='review.pollquestion'),
        ),
        migrations.AlterField(
            model_name='pollquestion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='events.event'),
        ),
    ]
