# Generated by Django 5.1.5 on 2025-04-15 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_alter_polloption_question_alter_pollquestion_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polloption',
            old_name='crearted_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='pollquestion',
            old_name='crearted_at',
            new_name='created_at',
        ),
    ]
