# Generated by Django 5.1.5 on 2025-04-15 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_rename_crearted_at_polloption_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pollquestion',
            options={'get_latest_by': 'crearted_at'},
        ),
        migrations.AddField(
            model_name='polloption',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
