# Generated by Django 5.1.5 on 2025-04-16 19:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_eventreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
