# Generated by Django 5.1.5 on 2025-01-22 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Event', models.CharField(max_length=100)),
                ('certificate_for', models.CharField(choices=[('Participation', 'Participation'), ('Winner', 'Winner'), ('Runner Up', 'Runner Up'), ('Second Runner-Up', 'Second Runner-Up')], default='Participation', max_length=100)),
                ('certificate_ss', models.ImageField(blank=True, null=True, upload_to='certificates_ss/')),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
