# Generated by Django 5.1.5 on 2025-01-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificatefor',
            options={'verbose_name_plural': 'Certificate Achievements'},
        ),
    ]
