# Generated by Django 5.1.5 on 2025-01-22 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='Event',
            new_name='event',
        ),
    ]
