# Generated by Django 5.1.5 on 2025-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_alter_certificatefor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-issue_date'], 'verbose_name': '1. Certificate'},
        ),
        migrations.AlterModelOptions(
            name='certificatefor',
            options={'verbose_name': '2. Certificate Achievement'},
        ),
    ]
