# Generated by Django 5.1.5 on 2025-04-17 12:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_alter_certificate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='hash',
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
