# Generated by Django 5.1.5 on 2025-02-17 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousYearQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=30)),
                ('year', models.CharField(max_length=10)),
                ('paper', models.FileField(upload_to='previous_year_question_paper/')),
                ('which_year', models.CharField(blank=True, max_length=100, null=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
