# Generated by Django 5.1.5 on 2025-02-17 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_previousyearquestionpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearquestionpaper',
            name='course',
            field=models.CharField(choices=[('BCA', 'BCA'), ('MCA', 'MCA'), ('BTECH', 'BTECH'), ('DIPLOMA', 'DIPLOMA')], max_length=30),
        ),
    ]
