# Generated by Django 5.1.5 on 2025-01-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_event_event_open_event_registration_open'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
