# Generated by Django 5.1.5 on 2025-02-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_previousyearquestionpaper_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previousyearquestionpaper',
            name='year',
            field=models.CharField(choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV')], max_length=10),
        ),
    ]
