# Generated by Django 5.1.5 on 2025-01-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_eventsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsubmission',
            name='attendence',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
